#!/usr/bin/env python3
"""Cloud Evolutionary Engine (Phase 16 port of scripts/evolutionary-engine/evolve.sh).

Runs on a GitHub-hosted runner. Uses cloud-brain-proxy (not the local blind-proxy)
to analyze a target source file and propose ONE performance/robustness improvement
as a unified diff. Safety (mirrors §1.4 verify-don't-assume of the local engine):

  1. The LLM must return a valid unified diff (or NO-OPT).
  2. `git apply --check` must pass (well-formed against the checked-out tree).
  3. The change is written to a NEW BRANCH and pushed; a PR is opened via the
     GitHub API. It is NEVER committed straight to main and NEVER auto-merged —
     a human (or a separate gate) reviews it. This is stricter than a stateless
     runner running pytest, since the runner has no local test rig for the box.

Env:
  GITHUB_TOKEN        push + PR (provided automatically in Actions)
  GITHUB_REPOSITORY   owner/repo (provided automatically in Actions)
  EVOLVE_TARGET       file to analyze (default: cloud-agents/asi_cloud.py)
  (+ BRAIN_URL / PROXY_AUTH_TOKEN from asi_cloud)
"""
import json
import os
import subprocess
import time
import urllib.request

import asi_cloud as asi

REPO = os.environ.get("GITHUB_REPOSITORY", "")
GH_TOKEN = os.environ.get("GITHUB_TOKEN", "")
TARGET = os.environ.get("EVOLVE_TARGET", "cloud-agents/asi_cloud.py")
UA = "asi-evolutionary"

SYSTEM = (
    "You are a senior engineer improving a Python file. Propose EXACTLY ONE small, "
    "safe improvement (performance, robustness, or clarity). Output ONLY a unified "
    "diff starting with '--- a/<path>' and '+++ b/<path>' that applies cleanly with "
    "`git apply`. If nothing is worth changing, output exactly: NO-OPT. No prose."
)


def sh(*args, check=True):
    r = subprocess.run(args, capture_output=True, text=True)
    if check and r.returncode != 0:
        raise RuntimeError(f"{' '.join(args)} -> {r.returncode}\n{r.stderr}")
    return r


def gh_api(method, path, body=None):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(
        f"https://api.github.com/{path}", data=data, method=method,
        headers={"Authorization": f"Bearer {GH_TOKEN}",
                 "Accept": "application/vnd.github+json", "User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read().decode())


def main():
    if not os.path.exists(TARGET):
        asi.log_run("evolutionary", "skip", f"target missing: {TARGET}")
        print("target missing:", TARGET)
        return 0

    src = open(TARGET, encoding="utf-8").read()
    prompt = (f"File path: {TARGET}\n\n```python\n{src[:12000]}\n```\n\n"
              "Return one improvement as a git-applyable unified diff, or NO-OPT.")
    try:
        diff = asi.ask(prompt, system=SYSTEM, temperature=0.2, max_tokens=1500).strip()
    except asi.ASIError as e:
        asi.log_run("evolutionary", "error", f"LLM failed: {e}")
        print("LLM failed:", e)
        return 1

    if diff.startswith("```"):
        diff = diff.strip("`").split("\n", 1)[-1] if "\n" in diff else diff
        diff = diff.replace("diff\n", "", 1).replace("patch\n", "", 1)
    if "NO-OPT" in diff or "--- a/" not in diff:
        asi.log_run("evolutionary", "no-opt", "agent found nothing worth changing")
        print("NO-OPT")
        return 0

    open("/tmp/evolve.patch", "w").write(diff if diff.endswith("\n") else diff + "\n")
    chk = sh("git", "apply", "--check", "/tmp/evolve.patch", check=False)
    if chk.returncode != 0:
        asi.log_run("evolutionary", "reject", f"diff did not apply cleanly:\n{chk.stderr[:500]}")
        print("diff rejected (git apply --check failed):", chk.stderr[:300])
        return 0

    branch = f"evolve/{int(time.time())}"
    sh("git", "config", "user.name", "asi-evolutionary")
    sh("git", "config", "user.email", "asi-evolutionary@users.noreply.github.com")
    sh("git", "checkout", "-b", branch)
    sh("git", "apply", "/tmp/evolve.patch")
    sh("git", "add", "-A")
    sh("git", "commit", "-m", f"evolve: auto-improvement to {TARGET}")
    remote = f"https://x-access-token:{GH_TOKEN}@github.com/{REPO}.git"
    sh("git", "push", remote, branch)

    pr = gh_api("POST", f"repos/{REPO}/pulls", {
        "title": f"[evolutionary] auto-improvement to {TARGET}",
        "head": branch, "base": "main",
        "body": "Auto-generated by the cloud Evolutionary Engine (Phase 16). "
                "Passed `git apply --check`. Human review required before merge.",
    })
    url = pr.get("html_url", "?")
    asi.log_run("evolutionary", "pr-opened", f"{TARGET} -> {url}")
    print("PR opened:", url)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
